import {
  type Umi,
  type TransactionBuilder,
  createNoopSigner,
  publicKey as toPublicKey,
  sol,
} from '@metaplex-foundation/umi';
import { base64 } from '@metaplex-foundation/umi/serializers';
import { findAssetSignerPda } from '@metaplex-foundation/mpl-core';
import { transferSol } from '@metaplex-foundation/mpl-toolbox';
import { randomUUID } from 'crypto';
import { getConfig } from './config.js';
import type { AgentContext } from './types/agent.js';
import bs58 from 'bs58';

/**
 * Submits a transaction based on the agent mode.
 *
 * - **Public mode**: serialize to base64, send to the user's wallet via
 *   `transactionSender.sendAndAwait`, and return the confirmed signature once
 *   the user approves and signs. Throws if the user rejects, the approval
 *   times out, or the client disconnects.
 *
 * - **Autonomous mode**: sign with the agent keypair and submit directly to
 *   the Solana network; returns the signature.
 *
 * @returns the base58 transaction signature
 */
export async function submitOrSend(
  umi: Umi,
  builder: TransactionBuilder,
  context: AgentContext,
  options?: { message?: string; index?: number; total?: number }
): Promise<string> {
  const config = getConfig();

  if (config.AGENT_MODE === 'public') {
    if (!context.transactionSender) {
      throw new Error('No transaction sender available. Is the WebSocket server running?');
    }
    if (!context.walletAddress) {
      throw new Error('No wallet connected. Ask the user to connect their wallet first.');
    }

    const walletSigner = createNoopSigner(toPublicKey(context.walletAddress));

    // Prepend fee if agent is registered
    let feeSol: number | undefined;
    if (context.agentAssetAddress && context.agentFeeSol > 0) {
      const agentPda = findAssetSignerPda(umi, {
        asset: toPublicKey(context.agentAssetAddress),
      })[0];
      builder = transferSol(umi, {
        source: walletSigner,
        destination: agentPda,
        amount: sol(context.agentFeeSol),
      }).add(builder);
      feeSol = context.agentFeeSol;
    }

    const tx = await builder
      .setFeePayer(walletSigner)
      .buildAndSign(umi);

    const serialized = umi.transactions.serialize(tx);
    const txBase64 = base64.deserialize(serialized)[0];

    // Send to frontend and await user signature
    const signature = await context.transactionSender.sendAndAwait(txBase64, {
      message: options?.message,
      index: options?.index,
      total: options?.total,
      feeSol,
    });

    return signature;
  }

  // Autonomous mode: enforce per-tick tx cap before doing anything. The
  // worker loop attaches a shared TxCounter to the request context; chat
  // path leaves it null. Throwing here surfaces to the LLM as a tool
  // error, prompting the agent to stand down for the rest of the tick
  // (vs silently dropping a tx).
  if (context.txCounter && context.txCounter.count >= context.txCounter.max) {
    throw new Error(
      `Per-tick transaction cap reached (${context.txCounter.max}). ` +
      'Standing down until next tick.'
    );
  }

  // Autonomous mode: dry-run shortcut. Still build+sign so we exercise
  // the tx construction path (catches builder errors realistically), but
  // skip the broadcast/confirm. The synthetic signature is intentionally
  // non-base58 so it can't be confused with a real on-chain signature in
  // logs or the journal.
  if (config.AUTONOMOUS_DRY_RUN) {
    await builder.buildAndSign(umi);
    const fakeSig = `DRYRUN_${randomUUID().split('-')[0]}`;
    console.log(`[dry-run] would have submitted transaction (sig=${fakeSig})`);
    if (context.txCounter) context.txCounter.count += 1;
    return fakeSig;
  }

  // Autonomous mode: sign and submit
  const result = await builder.sendAndConfirm(umi);
  if (context.txCounter) context.txCounter.count += 1;
  return bs58.encode(result.signature);
}

/** True if a signature was generated by the dry-run shortcut, not by Solana. */
export function isDryRunSignature(sig: string): boolean {
  return sig.startsWith('DRYRUN_');
}
